AWSTemplateFormatVersion: '2010-09-09'
Description: VPC 및 네트워크 리소스 생성

Resources:
  # VPC Stack
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.21.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: my-vpc

  # Internet Gateway Stack
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: my-igw

  # Attachment Internet Gateway to VPC
  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Routing Table(Public)
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: name
          Value: my-rt-public

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Routing Table(Public)
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
        Tags:
          - Key: Name
            Value: my-rt-private

  PublicSubnet1:
    Type: AWS::EC2::Subnet

Outputs: PathToMasterStackFile